---
development:
  cloud_name: some_cloud_name
  api_key: 'some_api_key'
  api_secret: some_api_secret
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: some_cloud_name
  api_key: 'some_api_key'
  api_secret: some_api_secret
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: some_cloud_name
  api_key: 'some_api_key'
  api_secret: some_api_secret
  enhance_image_tag: true
  static_image_support: false
